spring.application.name=backend
spring.profiles.active=local
sidequest.supabase.url=${SUPABASE_URL:}
sidequest.supabase.secret-key=${SUPABASE_SECRET_KEY:}
sidequest.routing.api-key=${DISTANCE_API_KEY:}
openai.api.key=${OPENAI_API_KEY:}
